version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel-app
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=${APP_ENV}
      - APP_KEY=${APP_KEY}
      # Add more environment variables as needed
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: laravel-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}

  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    ports:
      - "8000:80" # Map host port 8000 to container port 80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

networks:
  default:
    driver: bridge
