version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: laravel-app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    environment:
      - APP_ENV=local
      - APP_KEY=base64:vcdt76YIOUf5udsHoH6h8fMLGTIsSDj+zXYMVDJGYCM=
      # Add more environment variables as needed
    depends_on:
      - mysql
    networks:
      - laravel-network
    command: >
      sh -c "composer install && composer dump-autoload && chmod -R 777 storage bootstrap/cache && php-fpm && php artisan migrate --seed"

  mysql:
    image: mysql:8
    container_name: laravel-mysql
    environment:
      MYSQL_ROOT_PASSWORD: erativedev123
      MYSQL_DATABASE: cabin_hotel
      MYSQL_USER: erativedev
      MYSQL_PASSWORD: erativedev123
    networks:
      - laravel-network
  
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    ports:
      - "80:80"  # Map host port 80 to container port 80 (HTTP)
      - "443:443"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - app
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge
