version: '3'
services:
  app:
    build: .
    volumes:
      - .:/var/www
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
  web:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www
  certbot:
    image: certbot/certbot
    volumes:
      - /etc/letsencrypt
    command: certonly --webroot --webroot-path=/var/www/public --email your_email@example.com --agree-tos -d your_domain.com
