version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=local
      - APP_KEY=base64:vcdt76YIOUf5udsHoH6h8fMLGTIsSDj+zXYMVDJGYCM=
      # Add more environment variables as needed
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: laravel-mysql
    environment:
      MYSQL_ROOT_PASSWORD: erativedev123
      MYSQL_DATABASE: cabin_hotel
      MYSQL_USER: erativedev
      MYSQL_PASSWORD: erativedev123

  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    ports:
      - "80:80"  # Map host port 80 to container port 80 (HTTP)
      - "443:443" # Map host port 443 to container port 443 (HTTPS)
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot-etc:/etc/letsencrypt # Let's Encrypt certificates directory
    depends_on:
      - app
    networks:
      - nginx-proxy

  certbot:
    image: certbot/certbot
    container_name: laravel-certbot
    volumes:
      - ./certbot-etc:/etc/letsencrypt
    command: certonly --webroot -w /var/www/certbot -d thecabinhotelgroup.com

networks:
  default:
    driver: bridge
  nginx-proxy:
    external: true
